apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: dragone
spec: 
  selector:
    matchLabels: 
      app: dragone 
  template:
    metadata:
      labels: 
        app: dragone
    spec:
      containers: 
      - name: dragone
        image: melvinsamuel070/dragone:3
        ports: 
        - containerPort: 3001